// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjEEETVcm0YM_ww85B6WrxPx2OPmBdgt8',
    appId: '1:1047674055777:web:90674ff71465e1e7ad0e20',
    messagingSenderId: '1047674055777',
    projectId: 'flutterapp-2b273',
    authDomain: 'flutterapp-2b273.firebaseapp.com',
    databaseURL: 'https://flutterapp-2b273-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-2b273.appspot.com',
    measurementId: 'G-LJ5BKMFWSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKH6eQFNETkWh9nMesk8XsAd4Pf9Ibyc',
    appId: '1:1047674055777:android:893a706f9b648226ad0e20',
    messagingSenderId: '1047674055777',
    projectId: 'flutterapp-2b273',
    databaseURL: 'https://flutterapp-2b273-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-2b273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjyGPFnAAWVPt6uoCfnR6N9mquk-rqRk',
    appId: '1:1047674055777:ios:063ad81b0ef989bdad0e20',
    messagingSenderId: '1047674055777',
    projectId: 'flutterapp-2b273',
    databaseURL: 'https://flutterapp-2b273-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-2b273.appspot.com',
    iosClientId: '1047674055777-kjsp77oavg9dq8tola1vod6mst0tdfet.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjyGPFnAAWVPt6uoCfnR6N9mquk-rqRk',
    appId: '1:1047674055777:ios:063ad81b0ef989bdad0e20',
    messagingSenderId: '1047674055777',
    projectId: 'flutterapp-2b273',
    databaseURL: 'https://flutterapp-2b273-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-2b273.appspot.com',
    iosClientId: '1047674055777-kjsp77oavg9dq8tola1vod6mst0tdfet.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
